services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://arcade_user:arcade_password@db:5432/arcade_db
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app/app
      - ./firebase:/app/firebase
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: arcade_db
      POSTGRES_USER: arcade_user
      POSTGRES_PASSWORD: arcade_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U arcade_user -d arcade_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: